# From https://github.com/redisson/redisson/blob/master/.travis.yml
language: csharp

dotnet: 2.0.3

notifications:
  email: false

matrix:
  - REDIS_VERSION=3.2.11 ./build.sh
  - REDIS_VERSION=4.0.8 ./build.sh

env:
  global:
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  - TMPDIR=/tmp

install:
  - export REDIS_BIN=$HOME/redis/${REDIS_VERSION}/bin
  - wget -c https://github.com/antirez/redis/archive/${REDIS_VERSION}.tar.gz -O redis-${REDIS_VERSION}.tar.gz
  - tar -xvf redis-${REDIS_VERSION}.tar.gz
  - make -C redis-${REDIS_VERSION} PREFIX=$HOME/redis/${REDIS_VERSION} install

before_script:
 - $REDIS_BIN/redis-server --daemonize yes
 - sleep 3
 - $REDIS_BIN/redis-cli PING
 - export REDIS_VERSION="$(redis-cli INFO SERVER | sed -n 2p)"
 - echo $REDIS_VERSION
 - redis-cli SHUTDOWN NOSAVE
