using System.Threading.Tasks;
using Xunit;

namespace StackExchange.Redis.Tests.RoundTripUnitTests;

public class StreamAddRoundTrip(ITestOutputHelper log)
{
    [Theory(Timeout = 1000)]
    [InlineData(false, "*10\r\n$4\r\nXADD\r\n$6\r\nstream\r\n$6\r\nMAXLEN\r\n$1\r\n~\r\n$2\r\n10\r\n$5\r\nLIMIT\r\n$1\r\n5\r\n$1\r\n*\r\n$5\r\nfield\r\n$5\r\nvalue\r\n")]
    [InlineData(true, "*11\r\n$4\r\nXADD\r\n$6\r\nstream\r\n$10\r\nNOMKSTREAM\r\n$6\r\nMAXLEN\r\n$1\r\n~\r\n$2\r\n10\r\n$5\r\nLIMIT\r\n$1\r\n5\r\n$1\r\n*\r\n$5\r\nfield\r\n$5\r\nvalue\r\n")]
    public async Task XAddNoMkStream(bool nomkstream, string requestResp)
    {
        var db = new RedisDatabase(null!, 0, null);
        RedisKey key = "stream";
        var pair = new NameValueEntry("field", "value");
        var idempotentId = default(StreamIdempotentId);
        var message = db.GetStreamAddMessage(
            key,
            StreamConstants.AutoGeneratedId,
            in idempotentId,
            maxLength: 10,
            useApproximateMaxLength: true,
            nomkstream: nomkstream,
            streamPair: pair,
            limit: 5,
            mode: StreamTrimMode.KeepReferences,
            flags: CommandFlags.None);

        var result = await TestConnection.ExecuteAsync(message, ResultProcessor.RedisValue, requestResp, "$3\r\n1-0\r\n", log: log);
        Assert.Equal("1-0", result);
    }
}
