using System;

namespace StackExchange.Redis
{
#pragma warning disable SA1310 // Field names should not contain underscore
#pragma warning disable SA1311 // Static readonly fields should begin with upper-case letter
    internal static class RedisLiterals
    {
        // unlike primary commands, these do not get altered by the command-map; we may as
        // well compute the bytes once and share them
        public static readonly RedisValue
            ACLCAT = RedisValue.FromRaw("ACLCAT"u8),
            ADDR = RedisValue.FromRaw("ADDR"u8),
            AFTER = RedisValue.FromRaw("AFTER"u8),
            AGGREGATE = RedisValue.FromRaw("AGGREGATE"u8),
            ALPHA = RedisValue.FromRaw("ALPHA"u8),
            AND = RedisValue.FromRaw("AND"u8),
            ANDOR = RedisValue.FromRaw("ANDOR"u8),
            ANY = RedisValue.FromRaw("ANY"u8),
            ASC = RedisValue.FromRaw("ASC"u8),
            BEFORE = RedisValue.FromRaw("BEFORE"u8),
            BIT = RedisValue.FromRaw("BIT"u8),
            BY = RedisValue.FromRaw("BY"u8),
            BYLEX = RedisValue.FromRaw("BYLEX"u8),
            BYSCORE = RedisValue.FromRaw("BYSCORE"u8),
            BYTE = RedisValue.FromRaw("BYTE"u8),
            CH = RedisValue.FromRaw("CH"u8),
            CHANNELS = RedisValue.FromRaw("CHANNELS"u8),
            COUNT = RedisValue.FromRaw("COUNT"u8),
            DB = RedisValue.FromRaw("DB"u8),
            @default = RedisValue.FromRaw("default"u8),
            DESC = RedisValue.FromRaw("DESC"u8),
            DIFF = RedisValue.FromRaw("DIFF"u8),
            DIFF1 = RedisValue.FromRaw("DIFF1"u8),
            DOCTOR = RedisValue.FromRaw("DOCTOR"u8),
            ENCODING = RedisValue.FromRaw("ENCODING"u8),
            EX = RedisValue.FromRaw("EX"u8),
            EXAT = RedisValue.FromRaw("EXAT"u8),
            EXISTS = RedisValue.FromRaw("EXISTS"u8),
            FIELDS = RedisValue.FromRaw("FIELDS"u8),
            FILTERBY = RedisValue.FromRaw("FILTERBY"u8),
            FLUSH = RedisValue.FromRaw("FLUSH"u8),
            FNX = RedisValue.FromRaw("FNX"u8),
            FREQ = RedisValue.FromRaw("FREQ"u8),
            FXX = RedisValue.FromRaw("FXX"u8),
            GET = RedisValue.FromRaw("GET"u8),
            GETKEYS = RedisValue.FromRaw("GETKEYS"u8),
            GETNAME = RedisValue.FromRaw("GETNAME"u8),
            GT = RedisValue.FromRaw("GT"u8),
            HISTORY = RedisValue.FromRaw("HISTORY"u8),
            ID = RedisValue.FromRaw("ID"u8),
            IDX = RedisValue.FromRaw("IDX"u8),
            IDLETIME = RedisValue.FromRaw("IDLETIME"u8),
            IDMP = RedisValue.FromRaw("IDMP"u8),
            IDMPAUTO = RedisValue.FromRaw("IDMPAUTO"u8),
            IDMP_DURATION = RedisValue.FromRaw("IDMP-DURATION"u8),
            IDMP_MAXSIZE = RedisValue.FromRaw("IDMP-MAXSIZE"u8),
            KEEPTTL = RedisValue.FromRaw("KEEPTTL"u8),
            KILL = RedisValue.FromRaw("KILL"u8),
            LADDR = RedisValue.FromRaw("LADDR"u8),
            LATEST = RedisValue.FromRaw("LATEST"u8),
            LEFT = RedisValue.FromRaw("LEFT"u8),
            LEN = RedisValue.FromRaw("LEN"u8),
            lib_name = RedisValue.FromRaw("lib-name"u8),
            lib_ver = RedisValue.FromRaw("lib-ver"u8),
            LIMIT = RedisValue.FromRaw("LIMIT"u8),
            LIST = RedisValue.FromRaw("LIST"u8),
            LT = RedisValue.FromRaw("LT"u8),
            MATCH = RedisValue.FromRaw("MATCH"u8),
            MALLOC_STATS = RedisValue.FromRaw("MALLOC-STATS"u8),
            MAX = RedisValue.FromRaw("MAX"u8),
            MAXAGE = RedisValue.FromRaw("MAXAGE"u8),
            MAXLEN = RedisValue.FromRaw("MAXLEN"u8),
            MIN = RedisValue.FromRaw("MIN"u8),
            MINMATCHLEN = RedisValue.FromRaw("MINMATCHLEN"u8),
            MODULE = RedisValue.FromRaw("MODULE"u8),
            NODES = RedisValue.FromRaw("NODES"u8),
            NOSAVE = RedisValue.FromRaw("NOSAVE"u8),
            NOT = RedisValue.FromRaw("NOT"u8),
            NOVALUES = RedisValue.FromRaw("NOVALUES"u8),
            NUMPAT = RedisValue.FromRaw("NUMPAT"u8),
            NUMSUB = RedisValue.FromRaw("NUMSUB"u8),
            NX = RedisValue.FromRaw("NX"u8),
            OBJECT = RedisValue.FromRaw("OBJECT"u8),
            ONE = RedisValue.FromRaw("ONE"u8),
            OR = RedisValue.FromRaw("OR"u8),
            PATTERN = RedisValue.FromRaw("PATTERN"u8),
            PAUSE = RedisValue.FromRaw("PAUSE"u8),
            PERSIST = RedisValue.FromRaw("PERSIST"u8),
            PING = RedisValue.FromRaw("PING"u8),
            PURGE = RedisValue.FromRaw("PURGE"u8),
            PX = RedisValue.FromRaw("PX"u8),
            PXAT = RedisValue.FromRaw("PXAT"u8),
            RANK = RedisValue.FromRaw("RANK"u8),
            REFCOUNT = RedisValue.FromRaw("REFCOUNT"u8),
            REPLACE = RedisValue.FromRaw("REPLACE"u8),
            RESET = RedisValue.FromRaw("RESET"u8),
            RESETSTAT = RedisValue.FromRaw("RESETSTAT"u8),
            REV = RedisValue.FromRaw("REV"u8),
            REWRITE = RedisValue.FromRaw("REWRITE"u8),
            RIGHT = RedisValue.FromRaw("RIGHT"u8),
            SAVE = RedisValue.FromRaw("SAVE"u8),
            SEGFAULT = RedisValue.FromRaw("SEGFAULT"u8),
            SET = RedisValue.FromRaw("SET"u8),
            SETINFO = RedisValue.FromRaw("SETINFO"u8),
            SETNAME = RedisValue.FromRaw("SETNAME"u8),
            SKIPME = RedisValue.FromRaw("SKIPME"u8),
            STATS = RedisValue.FromRaw("STATS"u8),
            STOP = RedisValue.FromRaw("STOP"u8),
            STORE = RedisValue.FromRaw("STORE"u8),
            TYPE = RedisValue.FromRaw("TYPE"u8),
            USERNAME = RedisValue.FromRaw("USERNAME"u8),
            WEIGHTS = RedisValue.FromRaw("WEIGHTS"u8),
            WITHMATCHLEN = RedisValue.FromRaw("WITHMATCHLEN"u8),
            WITHSCORES = RedisValue.FromRaw("WITHSCORES"u8),
            WITHVALUES = RedisValue.FromRaw("WITHVALUES"u8),
            XOR = RedisValue.FromRaw("XOR"u8),
            XX = RedisValue.FromRaw("XX"u8),

            // Sentinel Literals
            MASTERS = RedisValue.FromRaw("MASTERS"u8),
            MASTER = RedisValue.FromRaw("MASTER"u8),
            REPLICAS = RedisValue.FromRaw("REPLICAS"u8),
            SLAVES = RedisValue.FromRaw("SLAVES"u8),
            GETMASTERADDRBYNAME = RedisValue.FromRaw("GET-MASTER-ADDR-BY-NAME"u8),
            // RESET = RedisValue.FromRaw("RESET"u8),
            FAILOVER = RedisValue.FromRaw("FAILOVER"u8),
            SENTINELS = RedisValue.FromRaw("SENTINELS"u8),

            // Sentinel Literals as of 2.8.4
            MONITOR = RedisValue.FromRaw("MONITOR"u8),
            REMOVE = RedisValue.FromRaw("REMOVE"u8),
            // SET = RedisValue.FromRaw("SET"u8),

            // replication states
            connect = RedisValue.FromRaw("connect"u8),
            connected = RedisValue.FromRaw("connected"u8),
            connecting = RedisValue.FromRaw("connecting"u8),
            handshake = RedisValue.FromRaw("handshake"u8),
            none = RedisValue.FromRaw("none"u8),
            sync = RedisValue.FromRaw("sync"u8),

            MinusSymbol = RedisValue.FromRaw("-"u8),
            PlusSymbol = RedisValue.FromRaw("+"u8),
            Wildcard = RedisValue.FromRaw("*"u8),

            // Geo Radius/Search Literals
            BYBOX = RedisValue.FromRaw("BYBOX"u8),
            BYRADIUS = RedisValue.FromRaw("BYRADIUS"u8),
            FROMMEMBER = RedisValue.FromRaw("FROMMEMBER"u8),
            FROMLONLAT = RedisValue.FromRaw("FROMLONLAT"u8),
            STOREDIST = RedisValue.FromRaw("STOREDIST"u8),
            WITHCOORD = RedisValue.FromRaw("WITHCOORD"u8),
            WITHDIST = RedisValue.FromRaw("WITHDIST"u8),
            WITHHASH = RedisValue.FromRaw("WITHHASH"u8),

            // geo units
            ft = RedisValue.FromRaw("ft"u8),
            km = RedisValue.FromRaw("km"u8),
            m = RedisValue.FromRaw("m"u8),
            mi = RedisValue.FromRaw("mi"u8),

            // misc (config, etc)
            databases = RedisValue.FromRaw("databases"u8),
            master = RedisValue.FromRaw("master"u8),
            no = RedisValue.FromRaw("no"u8),
            normal = RedisValue.FromRaw("normal"u8),
            pubsub = RedisValue.FromRaw("pubsub"u8),
            replica = RedisValue.FromRaw("replica"u8),
            replica_read_only = RedisValue.FromRaw("replica-read-only"u8),
            replication = RedisValue.FromRaw("replication"u8),
            sentinel = RedisValue.FromRaw("sentinel"u8),
            server = RedisValue.FromRaw("server"u8),
            slave = RedisValue.FromRaw("slave"u8),
            slave_read_only = RedisValue.FromRaw("slave-read-only"u8),
            timeout = RedisValue.FromRaw("timeout"u8),
            yes = RedisValue.FromRaw("yes"u8);

        internal static RedisValue Get(Bitwise operation) => operation switch
        {
            Bitwise.And => AND,
            Bitwise.Or => OR,
            Bitwise.Xor => XOR,
            Bitwise.Not => NOT,
            Bitwise.Diff => DIFF,
            Bitwise.Diff1 => DIFF1,
            Bitwise.AndOr => ANDOR,
            Bitwise.One => ONE,
            _ => throw new ArgumentOutOfRangeException(nameof(operation)),
        };
    }
#pragma warning restore SA1310 // Field names should not contain underscore
#pragma warning restore SA1311 // Static readonly fields should begin with upper-case letter
}
