using System;

namespace StackExchange.Redis
{
    /// <summary>
    /// Constants representing values used in Redis Stream commands.
    /// </summary>
    internal static class StreamConstants
    {
        /// <summary>
        /// The "~" value used with the MAXLEN option.
        /// </summary>
        internal static readonly RedisValue ApproximateMaxLen = RedisValue.FromRaw("~"u8);

        /// <summary>
        /// The "*" value used with the XADD command.
        /// </summary>
        internal static readonly RedisValue AutoGeneratedId = RedisValue.FromRaw("*"u8);

        /// <summary>
        /// The "$" value used in the XGROUP command. Indicates reading only new messages from the stream.
        /// </summary>
        internal static readonly RedisValue NewMessages = RedisValue.FromRaw("$"u8);

        /// <summary>
        /// The "0" value used in the XGROUP command. Indicates reading all messages from the stream.
        /// </summary>
        internal static readonly RedisValue AllMessages = RedisValue.FromRaw("0"u8);

        /// <summary>
        /// The "-" value used in the XRANGE, XREAD, and XREADGROUP commands. Indicates the minimum message ID from the stream.
        /// </summary>
        internal static readonly RedisValue ReadMinValue = RedisValue.FromRaw("-"u8);

        /// <summary>
        /// The "+" value used in the XRANGE, XREAD, and XREADGROUP commands. Indicates the maximum message ID from the stream.
        /// </summary>
        internal static readonly RedisValue ReadMaxValue = RedisValue.FromRaw("+"u8);

        /// <summary>
        /// The ">" value used in the XREADGROUP command. Use this to read messages that have not been delivered to a consumer group.
        /// </summary>
        internal static readonly RedisValue UndeliveredMessages = RedisValue.FromRaw(">"u8);

        internal static readonly RedisValue Consumers = RedisValue.FromRaw("CONSUMERS"u8);

        internal static readonly RedisValue Count = RedisValue.FromRaw("COUNT"u8);

        internal static readonly RedisValue Create = RedisValue.FromRaw("CREATE"u8);

        internal static readonly RedisValue DeleteConsumer = RedisValue.FromRaw("DELCONSUMER"u8);

        internal static readonly RedisValue Destroy = RedisValue.FromRaw("DESTROY"u8);

        internal static readonly RedisValue Groups = RedisValue.FromRaw("GROUPS"u8);

        internal static readonly RedisValue JustId = RedisValue.FromRaw("JUSTID"u8);

        internal static readonly RedisValue SetId = RedisValue.FromRaw("SETID"u8);

        internal static readonly RedisValue MaxLen = RedisValue.FromRaw("MAXLEN"u8);
        internal static readonly RedisValue MinId = RedisValue.FromRaw("MINID"u8);

        internal static readonly RedisValue MkStream = RedisValue.FromRaw("MKSTREAM"u8);

        internal static readonly RedisValue Stream = RedisValue.FromRaw("STREAM"u8);

        private static readonly RedisValue KeepRef = RedisValue.FromRaw("KEEPREF"u8), DelRef = RedisValue.FromRaw("DELREF"u8), Acked = RedisValue.FromRaw("ACKED"u8);

        internal static readonly RedisValue Ids = RedisValue.FromRaw("IDS"u8);

        internal static RedisValue GetMode(StreamTrimMode mode) => mode switch
            {
                StreamTrimMode.KeepReferences => KeepRef,
                StreamTrimMode.DeleteReferences => DelRef,
                StreamTrimMode.Acknowledged => Acked,
                _ => throw new ArgumentOutOfRangeException(nameof(mode)),
            };
    }
}
