using System;

namespace StackExchange.Redis;

/// <summary>
/// Additional options for adding an entry to a stream; see <see cref="IDatabase.StreamAdd(RedisKey, NameValueEntry[], StreamAddOptions, CommandFlags)"/>.
/// </summary>
/// <remarks>
/// The default value of this type means "append a new entry, letting the server assign the id, creating the
/// stream if it does not already exist, without trimming" - i.e. a plain <c>XADD key * ...</c>.
/// </remarks>
public readonly struct StreamAddOptions
{
    // stored inverted, so that `default` means CreateStream=true; XADD creates the stream unless NOMKSTREAM
    // is specified, and the default of this type must match the default of the command
    private readonly bool _noMkStream;

    /// <summary>
    /// The ID to assign to the stream entry; defaults to an auto-generated ID ("*").
    /// </summary>
    /// <remarks>Mutually exclusive with <see cref="IdempotentId"/>.</remarks>
    public RedisValue? MessageId { get; init; }

    /// <summary>
    /// The idempotent producer (pid) and optionally id (iid) to use for this entry; the server assigns the
    /// entry ID in this mode. See <see cref="StreamIdempotentId"/> for more information of the idempotent API.
    /// </summary>
    /// <remarks>Mutually exclusive with <see cref="MessageId"/>.</remarks>
    public StreamIdempotentId IdempotentId { get; init; }

    /// <summary>
    /// Trim the stream to this maximum length (<c>MAXLEN</c>) after appending.
    /// </summary>
    /// <remarks>Mutually exclusive with <see cref="MinId"/>.</remarks>
    public long? MaxLength { get; init; }

    /// <summary>
    /// Trim entries with an ID lower than this (<c>MINID</c>) after appending.
    /// </summary>
    /// <remarks>Mutually exclusive with <see cref="MaxLength"/>.</remarks>
    public RedisValue MinId { get; init; }

    /// <summary>
    /// If true, the "~" argument is used to allow the stream to exceed the requested threshold by a small
    /// number. This improves performance when removing messages. Ignored when no threshold is specified.
    /// </summary>
    public bool Approximate { get; init; }

    /// <summary>
    /// Specifies the maximal count of entries that will be evicted; requires <see cref="Approximate"/>
    /// and a threshold.
    /// </summary>
    public long? Limit { get; init; }

    /// <summary>
    /// Determines how stream trimming should be performed.
    /// </summary>
    public StreamTrimMode TrimMode { get; init; }

    /// <summary>
    /// Whether to create the stream when the key does not exist; when false, <c>NOMKSTREAM</c> is used and
    /// the command returns a null value instead of creating the stream. Defaults to <c>true</c>.
    /// </summary>
    public bool CreateStream
    {
        get => !_noMkStream;
        init => _noMkStream = !value;
    }

    /// <summary>
    /// Whether a trim threshold (<c>MAXLEN</c> or <c>MINID</c>) has been specified.
    /// </summary>
    internal bool HasThreshold => MaxLength.HasValue || MinId.HasValue;

    /// <summary>
    /// The entry ID to send; the idempotent forms always let the server assign the ID.
    /// </summary>
    internal RedisValue EntryId => MessageId ?? StreamConstants.AutoGeneratedId;

    internal void ThrowIfInvalid()
    {
        if (MaxLength.HasValue && MinId.HasValue)
        {
            Throw($"{nameof(MaxLength)} and {nameof(MinId)} are mutually exclusive.");
        }
        if (MessageId.HasValue && IdempotentId.ArgCount != 0)
        {
            Throw($"{nameof(MessageId)} and {nameof(IdempotentId)} are mutually exclusive; the server assigns the entry ID when producing idempotently.");
        }
        if (Limit.HasValue)
        {
            // both of these are rejected by the server; fail earlier, and more clearly
            if (!HasThreshold)
            {
                Throw($"{nameof(Limit)} requires {nameof(MaxLength)} or {nameof(MinId)}.");
            }
            if (!Approximate)
            {
                Throw($"{nameof(Limit)} requires {nameof(Approximate)}.");
            }
        }

        static void Throw(string message) => throw new ArgumentException(message, "options");
    }
}
