using System.Threading.Tasks;

namespace StackExchange.Redis.Interpolated
{
    /// <summary>
    /// The commands that have actually moved to the RESP context surface. Everything else is generated by
    /// <c>[AutoDatabase]</c> and throws; see <c>TransitionalDatabase.cs</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This is the file that grows as the transition proceeds, and the only one that needs touching to
    /// move a command across: implementing a member here removes it from the generated set automatically,
    /// because the generator skips what the class implements itself.
    /// </para>
    /// <para>
    /// Note how little is here per command. The body is the whole implementation - no message type, no
    /// result processor, no overload ladder - because the command already exists on the context surface
    /// and this is purely the adapter from the old interface to it.
    /// </para>
    /// </remarks>
    internal sealed partial class TransitionalDatabase
    {
        // ---- strings ------------------------------------------------------------------------------------

        /// <inheritdoc/>
        public RedisValue StringGet(RedisKey key, CommandFlags flags = CommandFlags.None)
            => Wait(Context.Strings.Get(key, flags));

        /// <inheritdoc/>
        public Task<RedisValue> StringGetAsync(RedisKey key, CommandFlags flags = CommandFlags.None)
            => Context.Strings.Get(key, flags).AsTask();

        /// <inheritdoc/>
        public bool StringSet(RedisKey key, RedisValue value, System.TimeSpan? expiry = null, bool keepTtl = false, When when = When.Always, CommandFlags flags = CommandFlags.None)
            => Wait(Context.Strings.Set(key, value, Expiration.CreateOrKeepTtl(expiry, keepTtl), when, flags));

        /// <inheritdoc/>
        public Task<bool> StringSetAsync(RedisKey key, RedisValue value, System.TimeSpan? expiry = null, bool keepTtl = false, When when = When.Always, CommandFlags flags = CommandFlags.None)
            => Context.Strings.Set(key, value, Expiration.CreateOrKeepTtl(expiry, keepTtl), when, flags).AsTask();

        // the two legacy When/TimeSpan? shapes, which is what most existing callers actually bind to.
        // `When` converts implicitly to ValueCondition, and CreateOrKeepTtl is the same helper
        // RedisDatabase uses, so these are pure adapters with no second opinion about semantics.

        /// <inheritdoc/>
        public bool StringSet(RedisKey key, RedisValue value, System.TimeSpan? expiry, When when)
            => StringSet(key, value, expiry, keepTtl: false, when);

        /// <inheritdoc/>
        public bool StringSet(RedisKey key, RedisValue value, System.TimeSpan? expiry, When when, CommandFlags flags)
            => StringSet(key, value, expiry, keepTtl: false, when, flags);

        /// <inheritdoc/>
        public Task<bool> StringSetAsync(RedisKey key, RedisValue value, System.TimeSpan? expiry, When when)
            => StringSetAsync(key, value, expiry, keepTtl: false, when);

        /// <inheritdoc/>
        public Task<bool> StringSetAsync(RedisKey key, RedisValue value, System.TimeSpan? expiry, When when, CommandFlags flags)
            => StringSetAsync(key, value, expiry, keepTtl: false, when, flags);

        /// <inheritdoc/>
        public bool StringSet(RedisKey key, RedisValue value, Expiration expiry = default, ValueCondition when = default, CommandFlags flags = CommandFlags.None)
            => Wait(Context.Strings.Set(key, value, expiry, when, flags));

        /// <inheritdoc/>
        public Task<bool> StringSetAsync(RedisKey key, RedisValue value, Expiration expiry = default, ValueCondition when = default, CommandFlags flags = CommandFlags.None)
            => Context.Strings.Set(key, value, expiry, when, flags).AsTask();

        // ---- the sync bridge ----------------------------------------------------------------------------

        /// <summary>Block for an asynchronous result, applying the multiplexer's timeout.</summary>
        /// <remarks>
        /// <para>
        /// <b>Sync is deliberately deprioritised</b>, so this is the cheap version rather than the right
        /// one. A synchronously-completed result - notably a client-side cache hit - is taken directly and
        /// costs nothing. Anything else blocks on a <c>Task</c>, which is sync-over-async: the async path
        /// completes its task sources with <c>RunContinuationsAsynchronously</c> (see
        /// <c>ResultBox.cs</c>), so the completion needs a thread-pool thread while this one is blocked
        /// holding another. That is the failure mode SER307/SER308 exist to warn about.
        /// </para>
        /// <para>
        /// The proper fix is routing rather than waiting: <c>IRespExecutor</c> already has a synchronous
        /// <c>Send</c>, and <c>RespExecutor.Send</c> already uses it, so a context flag consulted by the
        /// one shared funnel would make every sync call complete inline and reduce this method to its fast
        /// path. Worth doing when sync stops being deprioritised - not before.
        /// </para>
        /// </remarks>
        private T Wait<T>(ValueTask<T> pending)
        {
            if (pending.IsCompletedSuccessfully) return pending.Result;

            #pragma warning disable SER308 // Blocking on a task through the library's Wait helpers
            return multiplexer.Wait(pending.AsTask());
            #pragma warning restore SER308
        }
    }
}
