using System;
using System.Threading;
using System.Threading.Tasks;
using StackExchange.Redis.Interfaces;

namespace StackExchange.Redis.Availability;

// The bulk of IDatabase/IDatabaseAsync is generated by [AutoDatabase]: every command is captured into a
// state struct and replayed against the currently-active member via the Execute/ExecuteAsync funnels below
// (so a call always lands on whichever member is active *now*). Only the members the generator deliberately
// skips - the Wait family, IsConnected, the batch/transaction factories, and the streaming scans (see
// MultiGroupDatabase.Scans.cs) - plus the properties and internal plumbing are hand-written here.
[AutoDatabase]
internal sealed partial class MultiGroupDatabase(MultiGroupMultiplexer parent, int database, object? asyncState)
    : IDatabase, IInternalDatabaseAsync
{
    /// <inheritdoc/>
    public RespDatabaseContext Context => new(GetContext());

    private RespContext? _context;

    /// <summary>The context surface over whichever member is currently active.</summary>
    /// <remarks>
    /// <para>
    /// <b>This used to throw.</b> What it needed was an executor that resolves the active member per
    /// send rather than at construction - which is what <see cref="RespGroupExecutor"/> is - because the
    /// context is built once and memoised, while the active member is the thing a group exists to change.
    /// </para>
    /// <para>
    /// Note what is <i>not</i> here: nothing about connecting, reconnecting, backlogs, slots or routing.
    /// The active member is an entire multiplexer with its own executor chain, and this hands the command
    /// to it. That is the whole of a group's job, and the reason this is short.
    /// </para>
    /// <para>
    /// <b>Where the 628 generated forwarding members eventually go.</b> Every one of them exists to
    /// capture a command's arguments, resolve the active member, and replay the call against it - because
    /// the decoration happens above the command surface. Once the decoration is an executor below it,
    /// those members have nothing left to do, and this property is the seam through which they leave.
    /// </para>
    /// </remarks>
    private RespContext GetContext()
    {
        if (_context is { } existing) return existing;

        // The command map is the deployment's, and only a member can tell us what it is - so if the group
        // is down right now we build a context and do NOT memoise it, rather than baking the default map
        // in for the life of the multiplexer. Everything else about the context is member-independent.
        var active = parent.TryGetActive();
        var context = new RespContext(
                active?.CommandMap ?? CommandMap.Default,
                database: Database,
                serverType: ServerType.Standalone)
            .WithExecutor(new RespGroupExecutor(() => ActiveExecutor, Database, DescribeUnavailable));

        if (active is not null) _context = context;
        return context;
    }

    private RespExecutorBase? ActiveExecutor
        => TryGetActiveDatabase() is IRespTarget target ? target.Context.Executor : null;

    private string DescribeUnavailable()
    {
        // the group's own wording rather than a second copy of it: this asks the same question the facade
        // asks and reports the answer, so the two cannot drift apart
        try
        {
            _ = parent.Active;
            return "No connection group member is available.";
        }
        catch (RedisConnectionException ex)
        {
            return ex.Message;
        }
    }

    /// <inheritdoc/>
    RespContext IRespTarget.Context => GetContext();

    public object? AsyncState => asyncState;
    public int Database => database < 0 ? GetActiveDatabase().Database : database;

    public IConnectionMultiplexer Multiplexer => parent;

    CancellationToken IInternalDatabaseAsync.GetNextFailover() => parent.GetNextFailover();

    DatabaseFeatureFlags IInternalDatabaseAsync.GetFeatures(out string name)
    {
        // fold in the currently-active member's features (when there is one) and label with its name
        var active = TryGetActiveDatabase();
        var features = active is null ? DatabaseFeatureFlags.None : active.GetFeatures(out _);
        name = ((IConnectionGroup)parent).ActiveMember?.Name ?? "";
        return features | DatabaseFeatureFlags.ConnectionGroup | DatabaseFeatureFlags.Failover;
    }

    // uses the active member's name (via GetFeatures) when a member is active
    public override string ToString() => this.BuildString();

    // for high DB numbers this might allocate even for null async-state scenarios; unavoidable for now
    private IDatabase GetActiveDatabase() => parent.Active.GetDatabase(database, asyncState);

    // non-throwing twin of GetActiveDatabase: returns null when the group currently has no active
    // member, for use by members that have an obvious trivial result when disconnected
    private IDatabase? TryGetActiveDatabase() => parent.TryGetActive()?.GetDatabase(database, asyncState);

    // ---- [AutoDatabase] funnels ---------------------------------------------------------------------
    // the generated explicit interface implementations funnel every captured call through these: we simply
    // forward to the currently-active member. Unlike RetryDatabase there is no key mapping to apply (we are
    // not rewriting keys), so the captured state's Map/UnMapper is never invoked.
    private TResult Execute<TState, TResult>(in TState state, AutoDatabaseSyncOperation<TState, TResult> operation)
        where TState : struct
        => operation(in state, GetActiveDatabase());

    private void Execute<TState>(in TState state, AutoDatabaseSyncOperation<TState> operation)
        where TState : struct
        => operation(in state, GetActiveDatabase());

    private Task<TResult> ExecuteAsync<TState, TResult>(in TState state, AutoDatabaseAsyncOperation<TState, TResult> operation)
        where TState : struct
        => operation(in state, GetActiveDatabase());

    private Task ExecuteAsync<TState>(in TState state, AutoDatabaseAsyncOperation<TState> operation)
        where TState : struct
        => operation(in state, GetActiveDatabase());

    // ---- members the generator deliberately skips (see AutoDatabaseGenerator.SkipMethod) -------------
    public IBatch CreateBatch(object? asyncState = null)
        => GetActiveDatabase().CreateBatch(asyncState);

    public ITransaction CreateTransaction(object? asyncState = null)
        => GetActiveDatabase().CreateTransaction(asyncState);

    ITransactionAsync IDatabaseAsync.CreateTransaction(object? asyncState) => CreateTransaction(asyncState);

    // status probe, not a server round-trip: trivially "not connected" when there is no active member
    public bool IsConnected(RedisKey key, CommandFlags flags = CommandFlags.None)
        => TryGetActiveDatabase()?.IsConnected(key, flags) ?? false;

    // routing lookup against the currently-active member; null / NoEndpoint when the group has none
    public System.Net.EndPoint? IdentifyEndpoint(RedisKey key = default, CommandFlags flags = CommandFlags.None)
        => TryGetActiveDatabase()?.IdentifyEndpoint(key, flags);

    public Task<System.Net.EndPoint?> IdentifyEndpointAsync(RedisKey key = default, CommandFlags flags = CommandFlags.None)
        => TryGetActiveDatabase()?.IdentifyEndpointAsync(key, flags) ?? MultiGroupMultiplexer.NoEndpoint;

    // the Wait family operates on caller-supplied Tasks, not server calls
    // forwarding is not using: these decorators must implement the interface in full, and the
    // implementation cannot be dropped while the interface declares it
    #pragma warning disable SER308 // Blocking on a task through the library's Wait helpers
    public bool TryWait(Task task) => GetActiveDatabase().TryWait(task);
    public void Wait(Task task) => GetActiveDatabase().Wait(task);
    public T Wait<T>(Task<T> task) => GetActiveDatabase().Wait(task);
    public void WaitAll(params Task[] tasks) => GetActiveDatabase().WaitAll(tasks);
    #pragma warning restore SER308
}
