using System;
using System.Threading;
using System.Threading.Tasks;
using StackExchange.Redis.Interfaces;

namespace StackExchange.Redis.Availability;

// The bulk of IDatabase/IDatabaseAsync is generated by [AutoDatabase]: every command is captured into a
// state struct and replayed against the currently-active member via the Execute/ExecuteAsync funnels below
// (so a call always lands on whichever member is active *now*). Only the members the generator deliberately
// skips - the Wait family, IsConnected, the batch/transaction factories, and the streaming scans (see
// MultiGroupDatabase.Scans.cs) - plus the properties and internal plumbing are hand-written here.
[AutoDatabase]
internal sealed partial class MultiGroupDatabase(MultiGroupMultiplexer parent, int database, object? asyncState)
    : IDatabase, IInternalDatabaseAsync
{
    /// <inheritdoc/>
    public RespDatabaseContext Context => new(GetContext());

    private RespContext? _context;

    /// <summary>The context surface over whichever member is currently active.</summary>
    /// <remarks>
    /// <para>
    /// <b>This used to throw.</b> What it needed was an executor that resolves the active member per
    /// send rather than at construction - which is what <see cref="RespGroupExecutor"/> is - because the
    /// context is built once and memoised, while the active member is the thing a group exists to change.
    /// </para>
    /// <para>
    /// Note what is <i>not</i> here: nothing about connecting, reconnecting, backlogs, slots or routing.
    /// The active member is an entire multiplexer with its own executor chain, and this hands the command
    /// to it. That is the whole of a group's job, and the reason this is short.
    /// </para>
    /// <para>
    /// <b>The command map comes from configuration, not connection state</b> - each member is configured
    /// separately, and the group takes the map from its members' configuration - so it answers while
    /// every member is down. The one thing that may not is the database INDEX: <c>-1</c> means "whatever
    /// the active member defaults to", which needs a member. An explicit index does not, and that context
    /// is buildable and cacheable with nothing reachable at all.
    /// </para>
    /// <para>
    /// <b>The cache is the active member's, resolved per command.</b> Not a shared group cache: a cached
    /// reply is only sound while the connection that produced it is the one being asked and its
    /// <c>CLIENT TRACKING</c> registration is still live, so serving member A's values while B is active
    /// would be wrong - and silently so. Per-member caches make a switch a no-op for correctness, and the
    /// existing "flush when tracking drops" rule already covers the case that actually matters, since a
    /// failover usually happens BECAUSE the old member's connection died. A switch away from a healthy
    /// member leaves its cache warm for switching back, which nuking a shared cache would throw away.
    /// </para>
    /// <para>
    /// <b>Knowing the replication topology would not change this.</b> The rule is not "the data might
    /// differ" - that is incidental - but that <i>a cache entry carries an implicit subscription, and
    /// subscriptions do not transfer</i>. <c>CLIENT TRACKING</c> is registered per connection, so
    /// inheriting A's entries while talking to B inherits no registration on B: those entries become
    /// unfalsifiable rather than merely possibly-stale, even if B's data is byte-identical. Active-active
    /// and geo-replication change the invalidation <i>latency</i> (bounded by replication lag rather than
    /// a round trip), which bounds a safe maximum age - not what happens on a switch.
    /// </para>
    /// <para>
    /// <b>Where the 628 generated forwarding members eventually go.</b> Every one of them exists to
    /// capture a command's arguments, resolve the active member, and replay the call against it - because
    /// the decoration happens above the command surface. Once the decoration is an executor below it,
    /// those members have nothing left to do, and this property is the seam through which they leave.
    /// </para>
    /// </remarks>
    private RespContext GetContext()
    {
        if (_context is { } existing) return existing;

        // `database` is the constructor's, not the Database PROPERTY: the property resolves -1 by asking
        // the active member what it defaults to, and therefore throws when the group is down. An explicit
        // index needs no member, so that context is fully determined and can be built and memoised while
        // nothing is reachable; a defaulted one genuinely cannot be known yet, and throwing there is what
        // the Database property already does.
        var resolved = database >= 0 ? database : Database;
        return _context = new RespContext(
                parent.CommandMap,
                database: resolved,
                serverType: ServerType.Standalone)
            .WithExecutor(new RespGroupExecutor(() => ActiveExecutor, resolved, DescribeUnavailable))
            .WithCacheResolver(() => parent.TryGetActive()?.ClientCache);
    }

    private RespExecutorBase? ActiveExecutor
        => TryGetActiveDatabase() is IRespTarget target ? target.Context.Executor : null;

    private string DescribeUnavailable()
    {
        // the group's own wording rather than a second copy of it: this asks the same question the facade
        // asks and reports the answer, so the two cannot drift apart
        try
        {
            _ = parent.Active;
            return "No connection group member is available.";
        }
        catch (RedisConnectionException ex)
        {
            return ex.Message;
        }
    }

    /// <inheritdoc/>
    RespContext IRespTarget.Context => GetContext();

    public object? AsyncState => asyncState;
    public int Database => database < 0 ? GetActiveDatabase().Database : database;

    public IConnectionMultiplexer Multiplexer => parent;

    CancellationToken IInternalDatabaseAsync.GetNextFailover() => parent.GetNextFailover();

    DatabaseFeatureFlags IInternalDatabaseAsync.GetFeatures(out string name)
    {
        // fold in the currently-active member's features (when there is one) and label with its name
        var active = TryGetActiveDatabase();
        var features = active is null ? DatabaseFeatureFlags.None : active.GetFeatures(out _);
        name = ((IConnectionGroup)parent).ActiveMember?.Name ?? "";
        return features | DatabaseFeatureFlags.ConnectionGroup | DatabaseFeatureFlags.Failover;
    }

    // uses the active member's name (via GetFeatures) when a member is active
    public override string ToString() => this.BuildString();

    // for high DB numbers this might allocate even for null async-state scenarios; unavoidable for now
    private IDatabase GetActiveDatabase() => parent.Active.GetDatabase(database, asyncState);

    // non-throwing twin of GetActiveDatabase: returns null when the group currently has no active
    // member, for use by members that have an obvious trivial result when disconnected
    private IDatabase? TryGetActiveDatabase() => parent.TryGetActive()?.GetDatabase(database, asyncState);

    // ---- [AutoDatabase] funnels ---------------------------------------------------------------------
    // the generated explicit interface implementations funnel every captured call through these: we simply
    // forward to the currently-active member. Unlike RetryDatabase there is no key mapping to apply (we are
    // not rewriting keys), so the captured state's Map/UnMapper is never invoked.
    private TResult Execute<TState, TResult>(in TState state, AutoDatabaseSyncOperation<TState, TResult> operation)
        where TState : struct
        => operation(in state, GetActiveDatabase());

    private void Execute<TState>(in TState state, AutoDatabaseSyncOperation<TState> operation)
        where TState : struct
        => operation(in state, GetActiveDatabase());

    private Task<TResult> ExecuteAsync<TState, TResult>(in TState state, AutoDatabaseAsyncOperation<TState, TResult> operation)
        where TState : struct
        => operation(in state, GetActiveDatabase());

    private Task ExecuteAsync<TState>(in TState state, AutoDatabaseAsyncOperation<TState> operation)
        where TState : struct
        => operation(in state, GetActiveDatabase());

    // ---- members the generator deliberately skips (see AutoDatabaseGenerator.SkipMethod) -------------
    public IBatch CreateBatch(object? asyncState = null)
        => GetActiveDatabase().CreateBatch(asyncState);

    public ITransaction CreateTransaction(object? asyncState = null)
        => GetActiveDatabase().CreateTransaction(asyncState);

    ITransactionAsync IDatabaseAsync.CreateTransaction(object? asyncState) => CreateTransaction(asyncState);

    // status probe, not a server round-trip: trivially "not connected" when there is no active member
    public bool IsConnected(RedisKey key, CommandFlags flags = CommandFlags.None)
        => TryGetActiveDatabase()?.IsConnected(key, flags) ?? false;

    // routing lookup against the currently-active member; null / NoEndpoint when the group has none
    public System.Net.EndPoint? IdentifyEndpoint(RedisKey key = default, CommandFlags flags = CommandFlags.None)
        => TryGetActiveDatabase()?.IdentifyEndpoint(key, flags);

    public Task<System.Net.EndPoint?> IdentifyEndpointAsync(RedisKey key = default, CommandFlags flags = CommandFlags.None)
        => TryGetActiveDatabase()?.IdentifyEndpointAsync(key, flags) ?? MultiGroupMultiplexer.NoEndpoint;

    // the Wait family operates on caller-supplied Tasks, not server calls
    // forwarding is not using: these decorators must implement the interface in full, and the
    // implementation cannot be dropped while the interface declares it
    #pragma warning disable SER308 // Blocking on a task through the library's Wait helpers
    public bool TryWait(Task task) => GetActiveDatabase().TryWait(task);
    public void Wait(Task task) => GetActiveDatabase().Wait(task);
    public T Wait<T>(Task<T> task) => GetActiveDatabase().Wait(task);
    public void WaitAll(params Task[] tasks) => GetActiveDatabase().WaitAll(tasks);
    #pragma warning restore SER308
}
