
namespace StackExchange.Redis
{
    /// <summary>
    /// Constants representing values used in Redis Stream commands.
    /// </summary>
    public static class StreamConstants
    {
        /// <summary>
        /// The "~" value used with the MAXLEN option.
        /// </summary>
        public static readonly RedisValue ApproximateMaxLen = "~";

        /// <summary>
        /// The "*" value used with the XADD command.
        /// </summary>
        public static readonly RedisValue AutoGeneratedId = "*";

        /// <summary>
        /// The "$" value used in the XGROUP command. Indicates reading only new messages from the stream.
        /// </summary>
        public static readonly RedisValue NewMessages = "$";

        /// <summary>
        /// The "-" value used in the XRANGE, XREAD, and XREADGROUP commands. Indicates the minimum message ID from the stream.
        /// </summary>
        public static readonly RedisValue ReadMinValue = "-";

        /// <summary>
        /// The "+" value used in the XRANGE, XREAD, and XREADGROUP commands. Indicates the maximum message ID from the stream.
        /// </summary>
        public static readonly RedisValue ReadMaxValue = "+";

        /// <summary>
        /// The ">" value used in the XREADGROUP command. Use this to read messages that have not been delivered to a consumer group.
        /// </summary>
        public static readonly RedisValue UndeliveredMessages = ">";

        internal static readonly RedisValue Consumers = "CONSUMERS";

        internal static readonly RedisValue Count = "COUNT";

        internal static readonly RedisValue Create = "CREATE";

        internal static readonly RedisValue Group = "GROUP";

        internal static readonly RedisValue Groups = "GROUPS";

        internal static readonly RedisValue JustId = "JUSTID";

        internal static readonly RedisValue MaxLen = "MAXLEN";

        internal static readonly RedisValue Stream = "STREAM";

        internal static readonly RedisValue Streams = "STREAMS";
    }
}
